coverage:
  range: 50...100
  notify:
    gitter:
      default:
        threshold: 0
        url: https://gitter.im/golemfactory/golem
  status:
    patch:
      default:
        target: 80
    project:
      default:
        target: auto
    changes: false
  ignore:
    - "golem/database/schemas"
    - "golem/envs/docker/benchmark/minilight/*"
    - "golem/testutils.py"
    - "golem/tools/pyuic.py"
    - "save/*"
    - "scripts/*"
    - "tests/*"
    - "conftest.py"
    - "setup.py"
    - "Installer/*"
    - "setup_util/*"
comment:
  layout: header, diff, changes, sunburst, uncovered
