# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nodetasks.ui'
#
# Created: Thu Apr 03 16:34:39 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NodeTasksWidget(object):
    def setupUi(self, NodeTasksWidget):
        NodeTasksWidget.setObjectName(_fromUtf8("NodeTasksWidget"))
        NodeTasksWidget.resize(755, 611)
        self.gridLayout_2 = QtGui.QGridLayout(NodeTasksWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.timeLeftInput = QtGui.QLineEdit(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLeftInput.sizePolicy().hasHeightForWidth())
        self.timeLeftInput.setSizePolicy(sizePolicy)
        self.timeLeftInput.setText(_fromUtf8(""))
        self.timeLeftInput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLeftInput.setReadOnly(True)
        self.timeLeftInput.setObjectName(_fromUtf8("timeLeftInput"))
        self.gridLayout.addWidget(self.timeLeftInput, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.cpuPowerInput = QtGui.QLineEdit(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpuPowerInput.sizePolicy().hasHeightForWidth())
        self.cpuPowerInput.setSizePolicy(sizePolicy)
        self.cpuPowerInput.setText(_fromUtf8(""))
        self.cpuPowerInput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cpuPowerInput.setReadOnly(True)
        self.cpuPowerInput.setObjectName(_fromUtf8("cpuPowerInput"))
        self.gridLayout.addWidget(self.cpuPowerInput, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(NodeTasksWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.activeChunkProgressBar = QtGui.QProgressBar(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeChunkProgressBar.sizePolicy().hasHeightForWidth())
        self.activeChunkProgressBar.setSizePolicy(sizePolicy)
        self.activeChunkProgressBar.setMinimumSize(QtCore.QSize(160, 0))
        self.activeChunkProgressBar.setProperty("value", 0)
        self.activeChunkProgressBar.setObjectName(_fromUtf8("activeChunkProgressBar"))
        self.gridLayout.addWidget(self.activeChunkProgressBar, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(NodeTasksWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.chunkShortDescrInput = QtGui.QLineEdit(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chunkShortDescrInput.sizePolicy().hasHeightForWidth())
        self.chunkShortDescrInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.chunkShortDescrInput.setFont(font)
        self.chunkShortDescrInput.setReadOnly(True)
        self.chunkShortDescrInput.setObjectName(_fromUtf8("chunkShortDescrInput"))
        self.gridLayout.addWidget(self.chunkShortDescrInput, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 3, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(10, 0, -1, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.allocatedTasksInput = QtGui.QLineEdit(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allocatedTasksInput.sizePolicy().hasHeightForWidth())
        self.allocatedTasksInput.setSizePolicy(sizePolicy)
        self.allocatedTasksInput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allocatedTasksInput.setReadOnly(True)
        self.allocatedTasksInput.setObjectName(_fromUtf8("allocatedTasksInput"))
        self.gridLayout_3.addWidget(self.allocatedTasksInput, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.localTaskProgressBar = QtGui.QProgressBar(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localTaskProgressBar.sizePolicy().hasHeightForWidth())
        self.localTaskProgressBar.setSizePolicy(sizePolicy)
        self.localTaskProgressBar.setMinimumSize(QtCore.QSize(160, 0))
        self.localTaskProgressBar.setProperty("value", 0)
        self.localTaskProgressBar.setObjectName(_fromUtf8("localTaskProgressBar"))
        self.gridLayout_3.addWidget(self.localTaskProgressBar, 6, 1, 1, 1)
        self.label_13 = QtGui.QLabel(NodeTasksWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_14 = QtGui.QLabel(NodeTasksWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_15 = QtGui.QLabel(NodeTasksWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_16 = QtGui.QLabel(NodeTasksWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 5, 0, 1, 1)
        self.allocatedChunksInput = QtGui.QLineEdit(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allocatedChunksInput.sizePolicy().hasHeightForWidth())
        self.allocatedChunksInput.setSizePolicy(sizePolicy)
        self.allocatedChunksInput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allocatedChunksInput.setReadOnly(True)
        self.allocatedChunksInput.setObjectName(_fromUtf8("allocatedChunksInput"))
        self.gridLayout_3.addWidget(self.allocatedChunksInput, 2, 1, 1, 1)
        self.activeTasksInput = QtGui.QLineEdit(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeTasksInput.sizePolicy().hasHeightForWidth())
        self.activeTasksInput.setSizePolicy(sizePolicy)
        self.activeTasksInput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.activeTasksInput.setReadOnly(True)
        self.activeTasksInput.setObjectName(_fromUtf8("activeTasksInput"))
        self.gridLayout_3.addWidget(self.activeTasksInput, 3, 1, 1, 1)
        self.activeChunksInput = QtGui.QLineEdit(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeChunksInput.sizePolicy().hasHeightForWidth())
        self.activeChunksInput.setSizePolicy(sizePolicy)
        self.activeChunksInput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.activeChunksInput.setReadOnly(True)
        self.activeChunksInput.setObjectName(_fromUtf8("activeChunksInput"))
        self.gridLayout_3.addWidget(self.activeChunksInput, 4, 1, 1, 1)
        self.chunksLeftInput = QtGui.QLineEdit(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chunksLeftInput.sizePolicy().hasHeightForWidth())
        self.chunksLeftInput.setSizePolicy(sizePolicy)
        self.chunksLeftInput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.chunksLeftInput.setReadOnly(True)
        self.chunksLeftInput.setObjectName(_fromUtf8("chunksLeftInput"))
        self.gridLayout_3.addWidget(self.chunksLeftInput, 5, 1, 1, 1)
        self.label_17 = QtGui.QLabel(NodeTasksWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.locTaskShortDescrInput = QtGui.QLineEdit(NodeTasksWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locTaskShortDescrInput.sizePolicy().hasHeightForWidth())
        self.locTaskShortDescrInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.locTaskShortDescrInput.setFont(font)
        self.locTaskShortDescrInput.setObjectName(_fromUtf8("locTaskShortDescrInput"))
        self.gridLayout_3.addWidget(self.locTaskShortDescrInput, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.labelDetailedLocalTask = QtGui.QLabel(NodeTasksWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDetailedLocalTask.setFont(font)
        self.labelDetailedLocalTask.setObjectName(_fromUtf8("labelDetailedLocalTask"))
        self.gridLayout_2.addWidget(self.labelDetailedLocalTask, 2, 0, 1, 1)
        self.nodeUidLabel = QtGui.QLabel(NodeTasksWidget)
        self.nodeUidLabel.setObjectName(_fromUtf8("nodeUidLabel"))
        self.gridLayout_2.addWidget(self.nodeUidLabel, 0, 0, 1, 1)
        self.labelDetailedRemoteTask = QtGui.QLabel(NodeTasksWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDetailedRemoteTask.setFont(font)
        self.labelDetailedRemoteTask.setObjectName(_fromUtf8("labelDetailedRemoteTask"))
        self.gridLayout_2.addWidget(self.labelDetailedRemoteTask, 2, 1, 1, 1)
        self.tableLocalTasks = QtGui.QTableWidget(NodeTasksWidget)
        self.tableLocalTasks.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableLocalTasks.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableLocalTasks.setObjectName(_fromUtf8("tableLocalTasks"))
        self.tableLocalTasks.setColumnCount(2)
        self.tableLocalTasks.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableLocalTasks.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableLocalTasks.setHorizontalHeaderItem(1, item)
        self.tableLocalTasks.horizontalHeader().setCascadingSectionResizes(False)
        self.tableLocalTasks.horizontalHeader().setDefaultSectionSize(173)
        self.tableLocalTasks.verticalHeader().setDefaultSectionSize(20)
        self.tableLocalTasks.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_2.addWidget(self.tableLocalTasks, 1, 0, 1, 1)
        self.tableRemoteChunks = QtGui.QTableWidget(NodeTasksWidget)
        self.tableRemoteChunks.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableRemoteChunks.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableRemoteChunks.setObjectName(_fromUtf8("tableRemoteChunks"))
        self.tableRemoteChunks.setColumnCount(2)
        self.tableRemoteChunks.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableRemoteChunks.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableRemoteChunks.setHorizontalHeaderItem(1, item)
        self.tableRemoteChunks.horizontalHeader().setDefaultSectionSize(173)
        self.tableRemoteChunks.verticalHeader().setDefaultSectionSize(20)
        self.tableRemoteChunks.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_2.addWidget(self.tableRemoteChunks, 1, 1, 1, 1)

        self.retranslateUi(NodeTasksWidget)
        QtCore.QMetaObject.connectSlotsByName(NodeTasksWidget)

    def retranslateUi(self, NodeTasksWidget):
        NodeTasksWidget.setWindowTitle(_translate("NodeTasksWidget", "Node Viewer", None))
        self.label_4.setText(_translate("NodeTasksWidget", "Time left", None))
        self.label_2.setText(_translate("NodeTasksWidget", "CPU power", None))
        self.label_3.setText(_translate("NodeTasksWidget", "Progress", None))
        self.label_11.setText(_translate("NodeTasksWidget", "Short description", None))
        self.label_12.setText(_translate("NodeTasksWidget", "Allocated tasks", None))
        self.label_13.setText(_translate("NodeTasksWidget", "Allocated chunks", None))
        self.label_14.setText(_translate("NodeTasksWidget", "Active tasks", None))
        self.label_15.setText(_translate("NodeTasksWidget", "Active chunks", None))
        self.label_16.setText(_translate("NodeTasksWidget", "Chunks left", None))
        self.label_17.setText(_translate("NodeTasksWidget", "Short description", None))
        self.labelDetailedLocalTask.setText(_translate("NodeTasksWidget", "Active local task (ID)", None))
        self.nodeUidLabel.setText(_translate("NodeTasksWidget", "TextLabel", None))
        self.labelDetailedRemoteTask.setText(_translate("NodeTasksWidget", "Active task chunk (ID)", None))
        item = self.tableLocalTasks.horizontalHeaderItem(0)
        item.setText(_translate("NodeTasksWidget", "Task ID", None))
        item = self.tableLocalTasks.horizontalHeaderItem(1)
        item.setText(_translate("NodeTasksWidget", "Local Tasks", None))
        item = self.tableRemoteChunks.horizontalHeaderItem(0)
        item.setText(_translate("NodeTasksWidget", "Task ID", None))
        item = self.tableRemoteChunks.horizontalHeaderItem(1)
        item.setText(_translate("NodeTasksWidget", "Remote Chunks", None))

