RAW_REPORT_ORIGINAL = {
    'streams':
        [
            {'index': 0, 'codec_name': 'h264',
             'codec_long_name': 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10',
             'profile': 'Main', 'codec_type': 'video',
             'codec_time_base': '1/48',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000', 'width': 1024,
             'height': 576, 'coded_width': 1024,
             'coded_height': 576, 'has_b_frames': 1,
             'sample_aspect_ratio': '1:1',
             'display_aspect_ratio': '16:9',
             'pix_fmt': 'yuv420p', 'level': 31,
             'color_range': 'tv',
             'color_space': 'smpte170m',
             'color_transfer': 'bt709',
             'color_primaries': 'smpte170m',
             'chroma_location': 'topleft',
             'field_order': 'progressive', 'refs': 1,
             'is_avc': 'true', 'nal_length_size': '4',
             'r_frame_rate': '24/1',
             'avg_frame_rate': '24/1',
             'time_base': '1/1000',
             'start_pts': 0, 'start_time': '0.000000',
             'bits_per_raw_sample': '8',
             'disposition': {'default': 1, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0}},
            {'index': 1, 'codec_name': 'aac',
             'codec_long_name': 'AAC (Advanced Audio Coding)',
             'profile': 'LC', 'codec_type': 'audio',
             'codec_time_base': '1/48000',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000', 'sample_fmt': 'fltp',
             'sample_rate': '48000', 'channels': 2,
             'channel_layout': 'stereo',
             'bits_per_sample': 0, 'r_frame_rate': '0/0',
             'avg_frame_rate': '0/0',
             'time_base': '1/1000',
             'start_pts': 12, 'start_time': '0.012000',
             'disposition': {'default': 1, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0}},
            {'index': 2, 'codec_name': 'subrip',
             'codec_long_name': 'SubRip subtitle',
             'codec_type': 'subtitle',
             'codec_time_base': '0/1',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000',
             'r_frame_rate': '0/0',
             'avg_frame_rate': '0/0',
             'time_base': '1/1000',
             'start_pts': 0, 'start_time': '0.000000',
             'duration_ts': 46665,
             'duration': '46.665000',
             'disposition': {'default': 1, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0},
             'tags': {'language': 'eng'}},
            {'index': 3, 'codec_name': 'subrip',
             'codec_long_name': 'SubRip subtitle',
             'codec_type': 'subtitle',
             'codec_time_base': '0/1',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000',
             'r_frame_rate': '0/0',
             'avg_frame_rate': '0/0',
             'time_base': '1/1000',
             'start_pts': 42, 'start_time': '0.042000',
             'disposition': {'default': 0, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0},
             'tags': {'language': 'hun'}},
            {'index': 4, 'codec_name': 'subrip',
             'codec_long_name': 'SubRip subtitle',
             'codec_type': 'subtitle',
             'codec_time_base': '0/1',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000',
             'r_frame_rate': '0/0',
             'avg_frame_rate': '0/0',
             'time_base': '1/1000',
             'start_pts': 42, 'start_time': '0.042000',
             'disposition': {'default': 0, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0},
             'tags': {'language': 'ger'}},
            {'index': 5, 'codec_name': 'subrip',
             'codec_long_name': 'SubRip subtitle',
             'codec_type': 'subtitle',
             'codec_time_base': '0/1',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000',
             'r_frame_rate': '0/0',
             'avg_frame_rate': '0/0',
             'time_base': '1/1000',
             'start_pts': 42, 'start_time': '0.042000',
             'disposition': {'default': 0, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0},
             'tags': {'language': 'fre'}},
            {'index': 6, 'codec_name': 'subrip',
             'codec_long_name': 'SubRip subtitle',
             'codec_type': 'subtitle',
             'codec_time_base': '0/1',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000',
             'r_frame_rate': '0/0',
             'avg_frame_rate': '0/0',
             'time_base': '1/1000',
             'start_pts': 42, 'start_time': '0.042000',
             'disposition': {'default': 0, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0},
             'tags': {'language': 'spa'}},
            {'index': 7, 'codec_name': 'subrip',
             'codec_long_name': 'SubRip subtitle',
             'codec_type': 'subtitle',
             'codec_time_base': '0/1',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000',
             'r_frame_rate': '0/0',
             'avg_frame_rate': '0/0',
             'time_base': '1/1000',
             'start_pts': 42, 'start_time': '0.042000',
             'disposition': {'default': 0, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0},
             'tags': {'language': 'ita'}},
            {'index': 8, 'codec_name': 'aac',
             'codec_long_name': 'AAC (Advanced Audio Coding)',
             'profile': 'LC', 'codec_type': 'audio',
             'codec_time_base': '1/22050',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000', 'sample_fmt': 'fltp',
             'sample_rate': '22050', 'channels': 1,
             'channel_layout': 'mono',
             'bits_per_sample': 0,
             'r_frame_rate': '0/0',
             'avg_frame_rate': '0/0',
             'time_base': '1/1000', 'start_pts': 9,
             'start_time': '0.009000',
             'disposition': {'default': 0, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0},
             'tags': {'language': 'eng',
                      'title': 'Commentary'}},
            {'index': 9, 'codec_name': 'subrip',
             'codec_long_name': 'SubRip subtitle',
             'codec_type': 'subtitle',
             'codec_time_base': '0/1',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000',
             'r_frame_rate': '0/0',
             'avg_frame_rate': '0/0',
             'time_base': '1/1000',
             'start_pts': 42, 'start_time': '0.042000',
             'disposition': {'default': 0, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0},
             'tags': {'language': 'jpn'}},
            {'index': 10, 'codec_name': 'subrip',
             'codec_long_name': 'SubRip subtitle',
             'codec_type': 'subtitle',
             'codec_time_base': '0/1',
             'codec_tag_string': '[0][0][0][0]',
             'codec_tag': '0x0000',
             'r_frame_rate': '0/0',
             'avg_frame_rate': '0/0',
             'time_base': '1/1000',
             'start_pts': 42, 'start_time': '0.042000',
             'disposition': {'default': 0, 'dub': 0,
                             'original': 0, 'comment': 0,
                             'lyrics': 0, 'karaoke': 0,
                             'forced': 0,
                             'hearing_impaired': 0,
                             'visual_impaired': 0,
                             'clean_effects': 0,
                             'attached_pic': 0,
                             'timed_thumbnails': 0}}],
    'format': {
        'filename': '/golem/resources/test5.mkv',
        'nb_streams': 11, 'nb_programs': 0,
        'format_name': 'matroska,webm',
        'format_long_name': 'Matroska / WebM',
        'start_time': '0.000000',
        'duration': '46.665000',
        'size': '31762747', 'bit_rate': '5445236',
        'probe_score': 100, 'tags': {
            'encoder': 'libebml v1.0.0 + libmatroska v1.0.0',
            'creation_time': '2010-08-21T18:06:43.000000Z',
            'TITLE': 'Big Buck Bunny - test 8',
            'DATE_RELEASED': '2010',
            'COMMENT': 'Matroska Validation File 8, secondary audio commentary '
                       'track, misc subtitle tracks'}}}
