#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class Wrapper(object):
    """
    Attributes:
     - msg_name
     - msg_bytes
     - request_id
    """


    def __init__(self, msg_name=None, msg_bytes=None, request_id=None,):
        self.msg_name = msg_name
        self.msg_bytes = msg_bytes
        self.request_id = request_id

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.msg_name = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.msg_bytes = iprot.readBinary()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.request_id = iprot.readBinary()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('Wrapper')
        if self.msg_name is not None:
            oprot.writeFieldBegin('msg_name', TType.STRING, 1)
            oprot.writeString(self.msg_name.encode('utf-8') if sys.version_info[0] == 2 else self.msg_name)
            oprot.writeFieldEnd()
        if self.msg_bytes is not None:
            oprot.writeFieldBegin('msg_bytes', TType.STRING, 2)
            oprot.writeBinary(self.msg_bytes)
            oprot.writeFieldEnd()
        if self.request_id is not None:
            oprot.writeFieldBegin('request_id', TType.STRING, 3)
            oprot.writeBinary(self.request_id)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(Wrapper)
Wrapper.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'msg_name', 'UTF8', None, ),  # 1
    (2, TType.STRING, 'msg_bytes', 'BINARY', None, ),  # 2
    (3, TType.STRING, 'request_id', 'BINARY', None, ),  # 3
)
fix_spec(all_structs)
del all_structs
