# Initialize magic CommandHelper with imports
from . import account  # noqa
from . import concent  # noqa
from . import debug  # noqa
from . import environments  # noqa
from . import network  # noqa
from . import payments  # noqa
from . import resources  # noqa
from . import settings  # noqa
from . import tasks  # noqa
from . import terms  # noqa
from . import test_task  # noqa
