---
- hosts: master
  remote_user: ubuntu
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup:
  roles:
    - buildbot-master
    - webserver

- hosts: linux_worker
  remote_user: ubuntu
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup:
  roles:
    - buildbot-worker-linux

- hosts: windows_worker
  gather_facts: False
  pre_tasks:
    - name: get windows user password
      local_action:
        module: ec2_win_password
        instance_id: "{{hostvars[inventory_hostname]['ec2_id']}}"
        region: us-east-1
        key_file: "~/.ssh/{{hostvars[inventory_hostname]['ec2_key_name']}}"
      register: win_password
      no_log: True
    - set_fact:
        ansible_password: "{{win_password['win_password']}}"
      no_log: True
    - setup:
  roles:
    - buildbot-worker-windows
