FROM ubuntu:trusty

MAINTAINER Marek Franciszkiewicz <marek.franciszkiewicz@imapp.pl>

# Prerequisites
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates apt-transport-https \
    wget curl \
    python-pip python-dev python \
    python-qt4 pyqt4-dev-tools \
    pkg-config g++ dh-autoreconf \
    libjpeg-dev zlib1g-dev libopenexr-dev libgmp-dev libffi-dev libssl-dev iptables \
    git mercurial sed

RUN hg clone http://bitbucket.org/anthony_tuininga/cx_freeze -r 352d0dda3c77 cx_freeze
RUN cd cx_freeze && sed -i '89s/.*/            if True:/' setup.py && python setup.py install
RUN rm -rf cx_freeze

# Initial installation for faster future rebuilds
RUN git clone https://github.com/golemfactory/golem -b pack_compat --depth 1
RUN cd golem && pip install -r requirements.txt
RUN cd golem && python setup.py develop
RUN chmod -R 777 golem

VOLUME /tmp /tmp

ADD entrypoint.sh /usr/bin/entrypoint.sh
ENTRYPOINT ["/usr/bin/entrypoint.sh"]
